import Link from 'next/link';
import type { ReactNode } from 'react';
import { revalidatePath } from 'next/cache';
import { getSupabaseAdmin, hasSupabaseAdminConfig } from '@/lib/supabaseAdmin';

export const dynamic = 'force-dynamic';

type Row = { id: number; name?: string | null };
const txt = (v: FormDataEntryValue | null) => String(v || '').trim();
const id = (v: FormDataEntryValue | null) => { const n = Number(txt(v)); return Number.isFinite(n) && n > 0 ? n : null; };
const opts = (rows: Row[], fallback: string) => rows.map((r) => <option key={r.id} value={r.id}>{r.name || `${fallback} #${r.id}`}</option>);
const field = (name: string, child: ReactNode) => <label className="setup-field"><span>{name}</span>{child}</label>;

async function addCity(fd: FormData) { 'use server'; const name = txt(fd.get('name')); if (!name) return; await getSupabaseAdmin().from('cities').upsert({ name }, { onConflict: 'name' }); revalidatePath('/admin-setup'); }
async function addSeason(fd: FormData) { 'use server'; const name = txt(fd.get('name')); if (!name) return; await getSupabaseAdmin().from('seasons').upsert({ name, start_date: txt(fd.get('start_date')) || null, end_date: txt(fd.get('end_date')) || null, is_active: txt(fd.get('is_active')) === 'on' }, { onConflict: 'name' }); revalidatePath('/admin-setup'); }
async function addCategory(fd: FormData) { 'use server'; const name = txt(fd.get('name')); if (!name) return; await getSupabaseAdmin().from('categories').upsert({ name, gender: txt(fd.get('gender')) || 'ERKEK' }, { onConflict: 'name,gender' }); revalidatePath('/admin-setup'); }
async function addVenue(fd: FormData) { 'use server'; const city_id = id(fd.get('city_id')); const name = txt(fd.get('name')); if (!city_id || !name) return; await getSupabaseAdmin().from('venues').insert({ city_id, name, address: txt(fd.get('address')) || null, court_count: Number(fd.get('court_count') || 1) }); revalidatePath('/admin-setup'); }
async function addClub(fd: FormData) { 'use server'; const city_id = id(fd.get('city_id')); const name = txt(fd.get('name')); if (!city_id || !name) return; await getSupabaseAdmin().from('clubs').insert({ city_id, name, short_name: txt(fd.get('short_name')) || null }); revalidatePath('/admin-setup'); }
async function addTeam(fd: FormData) { 'use server'; const club_id = id(fd.get('club_id')); const name = txt(fd.get('name')); if (!club_id || !name) return; await getSupabaseAdmin().from('teams').insert({ club_id, category_id: id(fd.get('category_id')), season_id: id(fd.get('season_id')), name }); revalidatePath('/admin-setup'); }
async function addPlayer(fd: FormData) { 'use server'; const first_name = txt(fd.get('first_name')); const last_name = txt(fd.get('last_name')); if (!first_name || !last_name) return; const sb = getSupabaseAdmin(); const { data } = await sb.from('players').insert({ first_name, last_name, license_no: txt(fd.get('license_no')) || null, jersey_no: id(fd.get('jersey_no')), birth_date: txt(fd.get('birth_date')) || null, position: txt(fd.get('position')) || null }).select('id').single(); const team_id = id(fd.get('team_id')); if (data?.id && team_id) await sb.from('player_team_registrations').insert({ player_id: data.id, team_id, season_id: id(fd.get('season_id')), is_active: true }); revalidatePath('/admin-setup'); }
async function addCompetition(fd: FormData) { 'use server'; const city_id = id(fd.get('city_id')); const name = txt(fd.get('name')); if (!city_id || !name) return; await getSupabaseAdmin().from('competitions').insert({ city_id, season_id: id(fd.get('season_id')), category_id: id(fd.get('category_id')), name, competition_type: txt(fd.get('competition_type')) || 'LEAGUE', league_level: txt(fd.get('league_level')) || 'NONE', is_independent: true, status: 'ACTIVE' }); revalidatePath('/admin-setup'); }
async function addCompetitionTeam(fd: FormData) { 'use server'; const competition_id = id(fd.get('competition_id')); const team_id = id(fd.get('team_id')); if (!competition_id || !team_id) return; const sb = getSupabaseAdmin(); const { data: c } = await sb.from('competitions').select('city_id,season_id,category_id,league_level').eq('id', competition_id).single(); const { data: t } = await sb.from('teams').select('club_id').eq('id', team_id).single(); await sb.from('competition_teams').upsert({ competition_id, team_id, club_id: t?.club_id || null, city_id: c?.city_id || null, season_id: c?.season_id || null, category_id: c?.category_id || null, league_level: c?.league_level || 'NONE', is_active: true }, { onConflict: 'competition_id,team_id' }); revalidatePath('/admin-setup'); }
async function addMatch(fd: FormData) { 'use server'; const home_team_id = id(fd.get('home_team_id')); const away_team_id = id(fd.get('away_team_id')); const venue_id = id(fd.get('venue_id')); const date = txt(fd.get('match_date')); const time = txt(fd.get('match_time')) || '10:00'; const match_kind = txt(fd.get('match_kind')) || 'OFFICIAL'; if (!home_team_id || !away_team_id || home_team_id === away_team_id || !venue_id || !date) return; await getSupabaseAdmin().from('matches').insert({ home_team_id, away_team_id, venue_id, competition_id: id(fd.get('competition_id')), match_datetime: `${date}T${time}:00`, match_kind, roster_limit: ['FRIENDLY','SPECIAL_MATCH'].includes(match_kind) ? 24 : 12, counts_for_standings: match_kind === 'OFFICIAL', counts_for_season_stats: ['OFFICIAL','TOURNAMENT'].includes(match_kind), status: 'PLANLANDI', match_type: ['OFFICIAL','TOURNAMENT'].includes(match_kind) ? 'RESMI' : 'OZEL', current_quarter: 1, clock_seconds: 600, home_score: 0, away_score: 0 }); revalidatePath('/admin-setup'); }

export default async function AdminSetupPage() {
  if (!hasSupabaseAdminConfig()) return <main className="dashboard"><div className="topbar"><b>NONSTOP Mini Admin Setup</b><Link href="/operator">Operatör</Link></div><section className="card">Supabase service key ayarı eksik.</section></main>;
  const sb = getSupabaseAdmin();
  const [citiesRes,seasonsRes,categoriesRes,venuesRes,clubsRes,teamsRes,competitionsRes,matchesRes] = await Promise.all([
    sb.from('cities').select('id,name').order('name'), sb.from('seasons').select('id,name').order('name'), sb.from('categories').select('id,name').order('name'), sb.from('venues').select('id,name').order('name'), sb.from('clubs').select('id,name').order('name'), sb.from('teams').select('id,name').order('name'), sb.from('competitions').select('id,name').order('name'), sb.from('mini_admin_recent_matches').select('*').limit(12)
  ]);
  const cities=(citiesRes.data||[]) as Row[], seasons=(seasonsRes.data||[]) as Row[], categories=(categoriesRes.data||[]) as Row[], venues=(venuesRes.data||[]) as Row[], clubs=(clubsRes.data||[]) as Row[], teams=(teamsRes.data||[]) as Row[], competitions=(competitionsRes.data||[]) as Row[], matches=(matchesRes.data||[]) as any[];
  return <main className="dashboard admin-setup-page"><div className="topbar"><b>NONSTOP Mini Admin Setup</b><div style={{display:'flex',gap:12}}><Link href="/operator">Operatör</Link><Link href="/live">Canlı Skor</Link></div></div>
    <section className="card admin-intro"><h1>V2.1.22AF Hazırlık Ekranı</h1><p>Bu ekran test ve saha hazırlığı içindir. Tam yönetici paneli V2.1.23'te ayrıca yapılacak.</p><div className="admin-badges"><span>İl</span><span>Salon</span><span>Kulüp</span><span>Takım</span><span>Oyuncu</span><span>Organizasyon</span><span>Maç</span></div></section>
    <section className="admin-grid">
      <form action={addCity} className="card setup-form"><h2>1. İl</h2>{field('İl adı',<input name="name" placeholder="Bursa" required />)}<button className="primary">Kaydet</button></form>
      <form action={addSeason} className="card setup-form"><h2>2. Sezon</h2>{field('Sezon adı',<input name="name" placeholder="2026-2027" required />)}<div className="two-col">{field('Başlangıç',<input name="start_date" type="date" />)}{field('Bitiş',<input name="end_date" type="date" />)}</div><label className="check-line"><input name="is_active" type="checkbox"/> Aktif</label><button className="primary">Kaydet</button></form>
      <form action={addCategory} className="card setup-form"><h2>3. Kategori</h2>{field('Kategori',<input name="name" placeholder="U14" required />)}{field('Cinsiyet',<select name="gender"><option value="ERKEK">Erkek</option><option value="KIZ">Kız</option></select>)}<button className="primary">Kaydet</button></form>
      <form action={addVenue} className="card setup-form"><h2>4. Salon</h2>{field('İl',<select name="city_id" required><option value="">Seç</option>{opts(cities,'İl')}</select>)}{field('Salon adı',<input name="name" required />)}{field('Adres',<input name="address" />)}{field('Saha sayısı',<input name="court_count" type="number" defaultValue="1" />)}<button className="primary">Kaydet</button></form>
      <form action={addClub} className="card setup-form"><h2>5. Kulüp</h2>{field('İl',<select name="city_id" required><option value="">Seç</option>{opts(cities,'İl')}</select>)}{field('Kulüp adı',<input name="name" required />)}{field('Kısa ad',<input name="short_name" />)}<button className="primary">Kaydet</button></form>
      <form action={addTeam} className="card setup-form"><h2>6. Takım</h2>{field('Kulüp',<select name="club_id" required><option value="">Seç</option>{opts(clubs,'Kulüp')}</select>)}{field('Kategori',<select name="category_id"><option value="">Seçmeden geç</option>{opts(categories,'Kategori')}</select>)}{field('Sezon',<select name="season_id"><option value="">Seçmeden geç</option>{opts(seasons,'Sezon')}</select>)}{field('Takım adı',<input name="name" placeholder="Final Spor U14" required />)}<button className="primary">Kaydet</button></form>
      <form action={addPlayer} className="card setup-form wide"><h2>7. Oyuncu</h2><div className="two-col">{field('Ad',<input name="first_name" required />)}{field('Soyad',<input name="last_name" required />)}</div><div className="two-col">{field('Lisans no',<input name="license_no" />)}{field('Forma no',<input name="jersey_no" type="number" />)}</div><div className="two-col">{field('Doğum tarihi',<input name="birth_date" type="date" />)}{field('Pozisyon',<input name="position" />)}</div><div className="two-col">{field('Takım',<select name="team_id"><option value="">Sonra bağla</option>{opts(teams,'Takım')}</select>)}{field('Sezon',<select name="season_id"><option value="">Seçmeden geç</option>{opts(seasons,'Sezon')}</select>)}</div><button className="primary">Kaydet</button></form>
      <form action={addCompetition} className="card setup-form wide"><h2>8. Organizasyon</h2><div className="two-col">{field('İl',<select name="city_id" required><option value="">Seç</option>{opts(cities,'İl')}</select>)}{field('Sezon',<select name="season_id"><option value="">Seçmeden geç</option>{opts(seasons,'Sezon')}</select>)}</div><div className="two-col">{field('Kategori',<select name="category_id"><option value="">Seçmeden geç</option>{opts(categories,'Kategori')}</select>)}{field('Lig seviyesi',<select name="league_level"><option value="NONE">Yok</option><option value="A">A</option><option value="B">B</option></select>)}</div><div className="two-col">{field('Tür',<select name="competition_type"><option value="LEAGUE">Lig</option><option value="TOURNAMENT">Turnuva</option><option value="FRIENDLY">Hazırlık</option><option value="SPECIAL_MATCH">Özel</option></select>)}{field('Ad',<input name="name" required />)}</div><button className="primary">Kaydet</button></form>
      <form action={addCompetitionTeam} className="card setup-form"><h2>9. Takımı Organizasyona Ekle</h2>{field('Organizasyon',<select name="competition_id" required><option value="">Seç</option>{opts(competitions,'Organizasyon')}</select>)}{field('Takım',<select name="team_id" required><option value="">Seç</option>{opts(teams,'Takım')}</select>)}<button className="primary">Ekle</button></form>
      <form action={addMatch} className="card setup-form wide"><h2>10. Maç Oluştur</h2><div className="two-col">{field('Salon',<select name="venue_id" required><option value="">Seç</option>{opts(venues,'Salon')}</select>)}{field('Organizasyon',<select name="competition_id"><option value="">Seçmeden geç</option>{opts(competitions,'Organizasyon')}</select>)}</div><div className="two-col">{field('Ev sahibi',<select name="home_team_id" required><option value="">Seç</option>{opts(teams,'Takım')}</select>)}{field('Misafir',<select name="away_team_id" required><option value="">Seç</option>{opts(teams,'Takım')}</select>)}</div><div className="two-col">{field('Tarih',<input name="match_date" type="date" required />)}{field('Saat',<input name="match_time" type="time" defaultValue="10:00" />)}</div>{field('Maç türü',<select name="match_kind"><option value="OFFICIAL">Resmi - 12</option><option value="TOURNAMENT">Turnuva - 12</option><option value="FRIENDLY">Hazırlık - 24</option><option value="SPECIAL_MATCH">Özel - 24</option></select>)}<button className="primary">Kaydet</button></form>
    </section>
    <section className="card latest-matches"><h2>Son Maçlar</h2>{matches.length===0?<p>Henüz maç yok.</p>:<div className="mini-table"><div className="mini-head"><span>Tarih</span><span>Salon</span><span>Maç</span><span>Tür</span><span>Durum</span></div>{matches.map((m)=><div key={m.match_id} className="mini-row"><span>{m.match_datetime?new Date(m.match_datetime).toLocaleString('tr-TR'):'-'}</span><span>{m.venue_name||'-'}</span><span>{m.home_team_name||'Ev'} - {m.away_team_name||'Misafir'}</span><span>{m.match_kind||'-'}</span><span>{m.status||'-'}</span></div>)}</div>}</section>
  </main>;
}
